### ISSUE TITLE
Support test functions that are located inside classes

### ISSUE THREAD

**Issue by smarie** [smarie/python-pytest-steps#16]
`ValueError: <function TestClass.test_xxx> uses no argument '________step_name_'`

It seems that test functions located inside classes are not supported yet.

**Comment by rplevka** [comment]
uhm...here i am :D

**Comment by smarie** [comment]
Thanks for caring! As of today as I wrote above, this would require a major non-trivial modification. 

A workaround is to use the "new" pytest style (i.e. no classes, just plain old functions in separate modules). But I understand that in large projects this might not be satisfying. 

I would gladly accept contributions on the topic if anyone feels ready to dig into dynamic code compilation.

**Comment by zeburek** [comment]
Looks like a MUSTHAVE feature

**Comment by smarie** [comment]
It seems that this is doable quite easily with current status of the code. I'll have a look.

**Comment by smarie** [comment]
Fixed in `1.7.0` (to be released in a few minutes)
