### ISSUE TITLE
order inverted

### ISSUE THREAD

**Issue by bevinhex** [smarie/python-pytest-steps#43]
![image](https://user-images.githubusercontent.com/9736688/130236036-5dcdad94-364d-4a33-853c-e339a02a41d9.png)
As can seen from the image, not sure with which plugin it is not coming along, but the step names are in wrong order

**Comment by smarie** [comment]
Thanks @bevinhex for the feedback !

Could you please provide a minimal reproducible example ? Indeed I can not try to solve your issue if I can not reproduce it locally :(  Usually this can be done by removing all your applicative code from the test, leaving only pytest-steps stuff, and probably reducing the number of steps, while still checking that the issue appears.

Let me know!

**Comment by smarie** [comment]
Hi @bevinhex , were you by any chance able to create a reproducible example for this issue ?
Thanks !

**Comment by smarie** [comment]
Closing the issue as missing a reproducible example. Feel free to reopen if needed !
