### ISSUE TITLE
pytest-harvest + pytest-steps: results_bag fixture is cross-step, how to get per-step?

### ISSUE THREAD

**Issue by j-carson** [smarie/python-pytest-steps#49]
I have just started using your pytest extensions - they are wonderful, thank you! 

I had a pytest-steps test with four steps, and each step saved the current value of a variable at the end of each step. The results_bag only had the value of the variable at the last step, and that value appeared in the row for the first step.

I fixed it by creating a per-step results bag fixture and using that in place of results_bag as the argument to my test.  Is this the best way to get my desired behavior?

```python

@pytest.fixture
@one_fixture_per_step
def step_bag(request):
    """pytest-harvest creates a results_bag per step so that it
    can calculate duration_ms per step, but results_bag seems
    to not be updated per step in my tests. This fixture
    explicitly grabs the current step's bag.

    Parameters
    ----------
    request: current running test object
        Fixture provided by pytest
    """
    return request.getfixturevalue("results_bag")
```

**Comment by smarie** [comment]
Fixed by #46
